# Generated by Django 3.0.3 on 2020-04-06 09:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200404_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='attitude',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 6, 9, 9, 45, 529381, tzinfo=utc)),
        ),
    ]
