# Generated by Django 3.0.3 on 2020-04-07 02:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200406_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 7, 2, 51, 43, 86617, tzinfo=utc)),
        ),
    ]
